apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: anirudhmr1274/sentify-backend:latest
        ports:
        - containerPort: 8080
        env:
        - name: ML_SERVICE_URL
          value: "http://ml-service:8000/analyze" # Points to the K8s service name above
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080